import React from 'react';
import { Language } from './types';

export const TEXTS: Record<Language, Record<string, string>> = {
  en: {
    // General
    'back': 'Back',
    'loading': 'Loading...',
    'error': 'An error occurred. Please try again.',
    'submit': 'Submit',
    'select_language': 'Select your language',
    'english': 'English',
    'russian': 'Русский',
    'georgian': 'ქართული',
    'home': 'Home',
    'menu': 'Menu',
    'close': 'Close',

    // Home Page
    'welcome_to_tbilisi': 'TOURSELF',
    'your_adventure_awaits': 'Quests, Guides, and Local Life.',
    'explore_local_guide': 'Explore Local Guide',
    'free_guide_desc': 'Discover top sites, restaurants, and services. Completely free.',
    'find_city_quests': 'Find City Quests',
    'paid_quests_desc': 'Unlock exciting, gamified tours to explore the city\'s secrets.',
    'discover_nearest_attraction': 'Discover your first Tbilisi attraction.',
    'nearest_to_you': 'The nearest to you now is:',
    'view_details': 'View Details',

    // Menu
    'how_quests_work': 'How Quest Tours Work',
    'faq': 'FAQ',
    'contact_us': 'Contact Us',
    'for_local_guides': 'For Local Guides',
    'login': 'Login',
    'logout': 'Logout',
    'my_dashboard': 'My Dashboard',

    // Guide
    'local_guide_title': 'Tbilisi Local Guide',
    'search_places': 'Search places...',
    'all': 'All',
    'sites': 'Sites',
    'restaurants': 'Restaurants',
    'services': 'Services',
    'contact': 'Contact',
    'get_directions': 'Get Directions',
    'ai_fun_fact': 'Get AI Fun Fact ✨',
    'show_closest': 'Show Closest',
    'sorted_closest': 'Sorted by Closest',
    'getting_location': 'Getting Location...',
    'location_error': 'Could not get location. Please enable it in browser settings.',

    // Quests
    'city_quests_title': 'Tbilisi City Quests',
    'filter_by': 'Filter by:',
    'difficulty': 'Difficulty',
    'duration': 'Duration',
    'category': 'Category',
    'easy': 'Easy',
    'medium': 'Medium',
    'hard': 'Hard',
    'minutes': 'minutes',
    'start_quest': 'Start Quest',
    'purchase_quest': 'Purchase Quest for $9.99',
    'quest_purchased': 'Quest Purchased!',
    'access_token_info': 'Your access token is:',

    // Gameplay
    'step': 'Step',
    'of': 'of',
    'your_answer': 'Your Answer',
    'feedback_correct': 'Correct! Proceed to the next step.',
    'wrong_answer': 'Incorrect. Please try again.',
    'wrong_answer_attempts': 'Incorrect. You have {count} attempts left.',
    'no_more_attempts': 'Incorrect. No more attempts. Moving on to the next step.',
    'get_a_hint': 'Get a hint',

    // Completion
    'quest_complete': 'Quest Complete!',
    'congratulations': 'Congratulations!',
    'completion_message': 'You have successfully completed the quest.',
    'certificate_of_completion': 'Certificate of Completion',
    'awarded_to': 'Awarded to',
    'for_completing': 'for completing the',
    'quest': 'quest on',
    'download_certificate': 'Download Certificate',
    'back_to_quests': 'Back to Quests',
    'share_result': 'Share Your Result',
    'correctly_answered': 'You correctly answered {correct} out of {total} questions!',
    
    // Checkout
    'secure_checkout': 'Secure Checkout',
    'full_name': 'Full Name',
    'email_address': 'Email Address',
    'messenger_contact': 'Telegram/WhatsApp (e.g., @username or phone)',
    'pay_now': 'Pay $9.99 Now',
    
    // Auth & Registration
    'login_to_your_account': 'Login to your account',
    'username': 'Username',
    'password': 'Password',
    'login_failed': 'Login failed. Please check your credentials.',
    'register_as_guide': 'Register as a Local Guide',
    'city': 'City',
    'country': 'Country',
    'contact_phone': 'Contact Phone (Telegram/WhatsApp)',
    'confirm_password': 'Confirm Password',
    'passwords_do_not_match': 'Passwords do not match.',
    'registration_successful': 'Registration successful! You can now log in.',
    'register': 'Register',
    
    // Admin
    'admin_dashboard': 'Admin Dashboard',
    'dashboard': 'Dashboard',
    'manage_quests': 'Manage Quests',
    'manage_guide': 'Manage Guide',
    'submissions': 'Submissions',
    'manage_guides': 'Manage Guides',
    'settings': 'Settings',
    'edit_pages': 'Edit Pages',
    'edit_page': 'Edit Page',
    'save_page': 'Save Page',
    'page_title': 'Page Title',
    'page_content': 'Page Content',
    'create_new_quest': 'Create New Quest',
    'edit_quest': 'Edit Quest',
    'quest_title': 'Quest Title',
    'quest_description': 'Quest Description',
    'main_image_url': 'Main Image',
    'price': 'Price',
    'save_quest': 'Save Quest',
    'delete': 'Delete',
    'add_step': 'Add Step',
    'quest_steps': 'Quest Steps',
    'edit_step': 'Edit Step',
    'clue': 'Clue',
    'step_image_url': 'Step Image',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'question_type': 'Question Type',
    'multiple_choice': 'Multiple Choice',
    'open_text': 'Open Text',
    'question': 'Question',
    'options_comma_separated': 'Options (comma-separated)',
    'correct_answer': 'Correct Answer',
    'correct_answers_comma_separated': 'Correct Answer(s) (comma-separated)',
    'hint_optional': 'Hint (optional)',
    'save_step': 'Save Step',
    'create_new_item': 'Create New Guide Item',
    'edit_guide_item': 'Edit Guide Item',
    'guide_item_title': 'Guide Item Title',
    'guide_item_description': 'Guide Item Description',
    'address': 'Address',
    'image_url': 'Image',
    'save_item': 'Save Item',
    'manage_reviews': 'Manage Reviews',
    'send_notification': 'Send Notification',
    'notification_title': 'Notification Title',
    'notification_message': 'Notification Message',
    'send': 'Send',
    'notification_sent': 'Notification sent!',
    'approve': 'Approve',
    'approved': 'Approved',
    'pending': 'Pending',
    'published': 'Published',
    'status': 'Status',
    'comment': 'Comment',
    'rating': 'Rating',
    'upload_image': 'Upload Image',
    'change_image': 'Change Image',
    'search_location': 'Search Location',
    'current_location': 'Current Location',
    'location_search_placeholder': 'e.g., Freedom Square, Tbilisi',
    'location_info': 'Location will be auto-updated with mock data.',
    'post_answer_image_optional': 'Post-Answer Image (optional)',
    'post_answer_info': 'Post-Answer Info',
    'approve_quest': 'Approve & Publish Quest',
    'submitted_by': 'Submitted by',
    'no_submissions': 'No new submissions.',
    'change_admin_password': 'Change Admin Password',
    'new_password': 'New Password',
    'save_password': 'Save Password',
    'password_changed': 'Password changed successfully (mock).',
    'guide_name': 'Guide Name',
    
    // Guide Dashboard
    'guide_dashboard': 'Guide Dashboard',
    'my_quests': 'My Quests',
    'create_quest': 'Create Quest',
    'submit_for_approval': 'Submit for Approval',

    // Notifications
    'notifications': 'Notifications',
    'notifications_prompt': 'Stay updated with new quests and special offers!',
    'allow_notifications': 'Allow',
    'no_thanks': 'No, thanks',
    'nearby_notification_title': "You're Nearby!",
    'nearby_notification_body': "You're just around the corner from {itemName}. Check it out!",

    // Reviews
    'reviews': 'Reviews',
    'average_rating': 'Average Rating',
    'leave_a_review': 'Leave a Review',
    'your_rating': 'Your Rating',
    'your_comment': 'Your Comment',
    'submit_review': 'Submit Review',
    'review_submitted': 'Thank you for your review!',
    'no_reviews_yet': 'No reviews yet. Be the first!',
  },
  ru: {
    // This would be fully translated in a real app
    'back': 'Назад',
    'loading': 'Загрузка...',
    'error': 'Произошла ошибка.',
    'submit': 'Отправить',
    'select_language': 'Выберите ваш язык',
    'english': 'English',
    'russian': 'Русский',
    'georgian': 'ქართული',
    'home': 'Главная',
    'menu': 'Меню',
    'close': 'Закрыть',
    'welcome_to_tbilisi': 'TOURSELF',
    'your_adventure_awaits': 'Quests, Guides, and Local Life.',
    'explore_local_guide': 'Изучить Гид по городу',
    'free_guide_desc': 'Откройте для себя лучшие места, рестораны и услуги.',
    'find_city_quests': 'Найти Городские Квесты',
    'paid_quests_desc': 'Разблокируйте захватывающие игровые туры.',
    'discover_nearest_attraction': 'Откройте для себя первую достопримечательность Тбилиси.',
    'nearest_to_you': 'Ближайшая к вам сейчас:',
    'view_details': 'Посмотреть детали',
    'how_quests_work': 'Как работают квесты',
    'faq': 'ЧаВо',
    'contact_us': 'Связаться с нами',
    'for_local_guides': 'Для местных гидов',
    'login': 'Войти',
    'logout': 'Выйти',
    'my_dashboard': 'Моя панель',
    'local_guide_title': 'Гид по Тбилиси',
    'search_places': 'Искать места...',
    'all': 'Все',
    'sites': 'Места',
    'restaurants': 'Рестораны',
    'services': 'Услуги',
    'contact': 'Контакт',
    'get_directions': 'Проложить маршрут',
    'ai_fun_fact': 'Получить интересный факт от ИИ ✨',
    'show_closest': 'Показать ближайшие',
    'sorted_closest': 'Сортировка по близости',
    'getting_location': 'Получение геолокации...',
    'location_error': 'Не удалось получить геолокацию.',
    'city_quests_title': 'Городские квесты Тбилиси',
    'difficulty': 'Сложность',
    'easy': 'Легко',
    'medium': 'Средне',
    'hard': 'Сложно',
    'start_quest': 'Начать квест',
    'login_to_your_account': 'Войдите в свой аккаунт',
    'username': 'Имя пользователя',
    'password': 'Пароль',
    'login_failed': 'Не удалось войти. Проверьте данные.',
    'register_as_guide': 'Зарегистрироваться как местный гид',
    'city': 'Город',
    'country': 'Страна',
    'contact_phone': 'Контактный телефон (Telegram/WhatsApp)',
    'confirm_password': 'Подтвердите пароль',
    'passwords_do_not_match': 'Пароли не совпадают.',
    'registration_successful': 'Регистрация прошла успешно! Теперь вы можете войти.',
    'register': 'Зарегистрироваться',
    'admin_dashboard': 'Панель администратора',
    'dashboard': 'Панель управления',
    'manage_quests': 'Управление квестами',
    'manage_guide': 'Управление гидом',
    'submissions': 'Заявки на публикацию',
    'manage_guides': 'Управление гидами',
    'settings': 'Настройки',
    'edit_pages': 'Edit Pages',
    'approve_quest': 'Одобрить и опубликовать квест',
    'submitted_by': 'Отправлено',
    'no_submissions': 'Нет новых заявок.',
    'published': 'Опубликовано',
    'guide_dashboard': 'Панель гида',
    'my_quests': 'Мои квесты',
    'create_quest': 'Создать квест',
    'submit_for_approval': 'Отправить на проверку',
    'post_answer_info': 'Информация после ответа',
    'share_result': 'Поделиться результатом',
    'correctly_answered': 'Вы правильно ответили на {correct} из {total} вопросов!',
  },
  ge: {
    // This would be fully translated in a real app
    'back': 'უკან',
    'loading': 'იტვირთება...',
    'error': 'მოხდა შეცდომა.',
    'submit': 'გაგზავნა',
    'select_language': 'აირჩიეთ თქვენი ენა',
    'english': 'English',
    'russian': 'Русский',
    'georgian': 'ქართული',
    'home': 'მთავარი',
    'menu': 'მენიუ',
    'close': 'დახურვა',
    'welcome_to_tbilisi': 'TOURSELF',
    'your_adventure_awaits': 'Quests, Guides, and Local Life.',
    'explore_local_guide': 'ადგილობრივი გიდის დათვალიერება',
    'free_guide_desc': 'აღმოაჩინეთ საუკეთესო ადგილები, რესტორნები და სერვისები.',
    'find_city_quests': 'იპოვეთ ქალაქის ქვესტები',
    'paid_quests_desc': 'გახსენით საინტერესო, თამაშით სავსე ტურები.',
    'discover_nearest_attraction': 'აღმოაჩინე თბილისის პირველი ღირსშესანიშნაობა.',
    'nearest_to_you': 'თქვენთან ყველაზე ახლოს არის:',
    'view_details': 'დეტალების ნახვა',
    'how_quests_work': 'როგორ მუშაობს ქვესტები',
    'faq': 'ხშირად დასმული კითხვები',
    'contact_us': 'დაგვიკავშირდით',
    'for_local_guides': 'ადგილობრივი გიდებისთვის',
    'login': 'შესვლა',
    'logout': 'გასვლა',
    'my_dashboard': 'ჩემი პანელი',
    'local_guide_title': 'თბილისის ადგილობრივი გიდი',
    'search_places': 'ადგილების ძებნა...',
    'all': 'ყველა',
    'sites': 'ადგილები',
    'restaurants': 'რესტორნები',
    'services': 'სერვისები',
    'contact': 'კონტაქტი',
    'get_directions': 'მიიღეთ მიმართულებები',
    'ai_fun_fact': 'მიიღეთ საინტერესო ფაქტი AI-სგან ✨',
    'show_closest': 'უახლოესის ჩვენება',
    'sorted_closest': 'დალაგებულია სიახლოვით',
    'getting_location': 'მდებარეობის მიღება...',
    'location_error': 'მდებარეობის მიღება ვერ მოხერხდა.',
    'city_quests_title': 'თბილისის ქალაქის ქვესტები',
    'difficulty': 'სირთულე',
    'easy': 'მარტივი',
    'medium': 'საშუალო',
    'hard': 'რთული',
    'start_quest': 'ქვესტის დაწყება',
    'login_to_your_account': 'შედით თქვენს ანგარიშზე',
    'username': 'მომხმარებლის სახელი',
    'password': 'პაროლი',
    'login_failed': 'შესვლა ვერ მოხერხდა. შეამოწმეთ მონაცემები.',
    'register_as_guide': 'დარეგისტრირდით როგორც ადგილობრივი გიდი',
    'city': 'ქალაქი',
    'country': 'ქვეყანა',
    'contact_phone': 'საკონტაქტო ტელეფონი (Telegram/WhatsApp)',
    'confirm_password': 'დაადასტურეთ პაროლი',
    'passwords_do_not_match': 'პაროლები არ ემთხვევა.',
    'registration_successful': 'რეგისტრაცია წარმატებულია! ახლა შეგიძლიათ შეხვიდეთ.',
    'register': 'რეგისტრაცია',
    'admin_dashboard': 'ადმინისტრატორის პანელი',
    'dashboard': 'მართვის პანელი',
    'manage_quests': 'ქვესტების მართვა',
    'manage_guide': 'გიდის მართვა',
    'submissions': 'განაცხადები',
    'manage_guides': 'გიდების მართვა',
    'settings': 'პარამეტრები',
    'edit_pages': 'Edit Pages',
    'approve_quest': 'ქვესტის დამტკიცება და გამოქვეყნება',
    'submitted_by': 'წარმოდგენილია',
    'no_submissions': 'ახალი განაცხადები არ არის.',
    'published': 'გამოქვეყნებულია',
    'guide_dashboard': 'გიდის პანელი',
    'my_quests': 'ჩემი ქვესტები',
    'create_quest': 'ქვესტის შექმნა',
    'submit_for_approval': 'გაგზავნა დასამტკიცებლად',
    'post_answer_info': 'ინფორმაცია პასუხის შემდეგ',
    'share_result': 'შედეგის გაზიარება',
    'correctly_answered': 'თქვენ სწორად უპასუხეთ {correct} კითხვას {total}-დან!',
  },
};

// SVG Icons
export const Icons = {
  MapPin: () => <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" /></svg>,
  Clock: () => <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.414-1.414L11 10.586V6z" clipRule="evenodd" /></svg>,
  BarChart: () => <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z" /><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z" /></svg>,
  ChevronLeft: () => <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>,
  ChevronRight: () => <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>,
  Sparkles: () => <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.293 2.293a1 1 0 010 1.414L15 6m0 0l-2.293 2.293a1 1 0 01-1.414 0L9 6m0 0l2.293-2.293a1 1 0 011.414 0L15 6m-2 14v-4m2 2h-4" /></svg>,
  Star: ({ className = '' }: { className?: string }) => <svg xmlns="http://www.w3.org/2000/svg" className={`h-5 w-5 ${className}`} viewBox="0 0 20 20" fill="currentColor"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" /></svg>,
  ListBullet: () => <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clipRule="evenodd" /></svg>,
  Speaker: () => <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M9.383 3.076A1 1 0 0110 4v12a1 1 0 01-1.707.707L4.586 13H2a1 1 0 01-1-1V8a1 1 0 011-1h2.586l3.707-3.707a1 1 0 011.09-.217zM14.657 2.929a1 1 0 011.414 0A9.972 9.972 0 0119 10a9.972 9.972 0 01-2.929 7.071 1 1 0 01-1.414-1.414A7.971 7.971 0 0017 10c0-2.21-.894-4.208-2.343-5.657a1 1 0 010-1.414zm-2.829 2.828a1 1 0 011.415 0A5.983 5.983 0 0115 10a5.984 5.984 0 01-1.757 4.243 1 1 0 01-1.415-1.415A3.984 3.984 0 0013 10a3.983 3.983 0 00-1.172-2.828 1 1 0 010-1.415z" clipRule="evenodd" /></svg>,
  Stop: () => <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8 7a1 1 0 00-1 1v4a1 1 0 001 1h4a1 1 0 001-1V8a1 1 0 00-1-1H8z" clipRule="evenodd" /></svg>,
  MapIcon: () => <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M17.293 3.293a1 1 0 011.414 0l.001.001c.39.39.39 1.022 0 1.414l-3 3a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l3-3a1 1 0 011.414 0zM15 5.414L12.414 8 15 10.586V5.414zM4.707 3.293a1 1 0 00-1.414 0l-3 3a1 1 0 000 1.414l4 4a1 1 0 001.414 0l3-3a1 1 0 000-1.414l-4-4zM5 8.414L7.586 11 5 13.586V8.414zM10.586 12L8 14.586 10.586 17H14v-2.414L11.414 12h-1.828z" clipRule="evenodd" /></svg>,
  Home: () => <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" viewBox="0 0 20 20" fill="currentColor"><path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" /></svg>,
  Menu: () => <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" /></svg>,
};